apiVersion: v1
kind: Service
metadata:
  name: hugio-app-user-svc
  labels:
    app: hugio-app-user
spec:
  type: NodePort
  selector:
    app: hugio-app-user
  ports:
    - protocol: 'TCP'
      name: http
      port: 4204
      targetPort: 90
