apiVersion: v1
kind: Service
metadata:
  name: hugio-app-chat-svc
  labels:
    app: hugio-app-chat
spec:
  type: NodePort
  selector:
    app: hugio-app-chat
  ports:
    - protocol: 'TCP'
      name: http
      port: 4208
      targetPort: 90
