apiVersion: v1
kind: Service
metadata:
  name: hugio-app-product-svc
  labels:
    app: hugio-app-product
spec:
  type: NodePort
  selector:
    app: hugio-app-product
  ports:
    - protocol: 'TCP'
      name: http
      port: 4205
      targetPort: 90
