apiVersion: v1
kind: Service
metadata:
  name: hugio-app-cashbook-svc
  labels:
    app: hugio-app-cashbook
spec:
  type: NodePort
  selector:
    app: hugio-app-cashbook
  ports:
    - protocol: 'TCP'
      name: http
      port: 4203
      targetPort: 90
