apiVersion: v1
kind: Service
metadata:
  name: hugio-app-summary-svc
  labels:
    app: hugio-app-summary
spec:
  type: NodePort
  selector:
    app: hugio-app-summary
  ports:
    - protocol: 'TCP'
      name: http
      port: 4201
      targetPort: 90
