apiVersion: v1
kind: Service
metadata:
  name: hugio-app-order-svc
  labels:
    app: hugio-app-order
spec:
  type: NodePort
  selector:
    app: hugio-app-order
  ports:
    - protocol: 'TCP'
      name: http
      port: 4207
      targetPort: 90
