apiVersion: apps/v1
kind: Deployment
metadata:
  name: hugio-app-chat
spec:
  selector:
    matchLabels:
      app: hugio-app-chat
  replicas: 1
  template:
    metadata:
      labels:
        app: hugio-app-chat
    spec:
      containers:
        - name: hugio-app-chat
          image: hugio/fe:app_chat
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 90
          env:
            - name: TZ
              value: 'Asia/Ho_Chi_Minh'
