apiVersion: v1
kind: Service
metadata:
  name: hugio-app-shell-svc
  labels:
    app: hugio-app-shell
spec:
  type: NodePort
  selector:
    app: hugio-app-shell
  ports:
    - protocol: 'TCP'
      name: http
      port: 4200
      targetPort: 90
